//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FireFly.CourseEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState MainForm_WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["MainForm_WindowState"]));
            }
            set {
                this["MainForm_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainForm_Visible {
            get {
                return ((bool)(this["MainForm_Visible"]));
            }
            set {
                this["MainForm_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FireFly course|*.zip")]
        public string CourseFileFilter {
            get {
                return ((string)(this["CourseFileFilter"]));
            }
            set {
                this["CourseFileFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Options_SaveRestoreWindowsState {
            get {
                return ((bool)(this["Options_SaveRestoreWindowsState"]));
            }
            set {
                this["Options_SaveRestoreWindowsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Options_ShowToolBar {
            get {
                return ((bool)(this["Options_ShowToolBar"]));
            }
            set {
                this["Options_ShowToolBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Delivery Controls")]
        public string DeliveryControlsType_ToString {
            get {
                return ((string)(this["DeliveryControlsType_ToString"]));
            }
            set {
                this["DeliveryControlsType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Objectives")]
        public string ObjectivesType_ToString {
            get {
                return ((string)(this["ObjectivesType_ToString"]));
            }
            set {
                this["ObjectivesType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rule")]
        public string RollupRuleType_ToString {
            get {
                return ((string)(this["RollupRuleType_ToString"]));
            }
            set {
                this["RollupRuleType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rollup Condition")]
        public string RollupRuleTypeRollupConditionsRollupCondition_ToString {
            get {
                return ((string)(this["RollupRuleTypeRollupConditionsRollupCondition_ToString"]));
            }
            set {
                this["RollupRuleTypeRollupConditionsRollupCondition_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rollup Action")]
        public string RollupRuleTypeRollupAction_ToString {
            get {
                return ((string)(this["RollupRuleTypeRollupAction_ToString"]));
            }
            set {
                this["RollupRuleTypeRollupAction_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rollup Rules")]
        public string RollupRulesType_ToString {
            get {
                return ((string)(this["RollupRulesType_ToString"]));
            }
            set {
                this["RollupRulesType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Limit Conditions")]
        public string LimitConditionsType_ToString {
            get {
                return ((string)(this["LimitConditionsType_ToString"]));
            }
            set {
                this["LimitConditionsType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PreCondition Rule")]
        public string PreConditionRuleType_ToString {
            get {
                return ((string)(this["PreConditionRuleType_ToString"]));
            }
            set {
                this["PreConditionRuleType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rule Action")]
        public string PreConditionRuleTypeRuleAction_ToString {
            get {
                return ((string)(this["PreConditionRuleTypeRuleAction_ToString"]));
            }
            set {
                this["PreConditionRuleTypeRuleAction_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Post Condition Rule")]
        public string PostConditionRuleType_ToString {
            get {
                return ((string)(this["PostConditionRuleType_ToString"]));
            }
            set {
                this["PostConditionRuleType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Exit Rule")]
        public string ExitConditionRuleType_ToString {
            get {
                return ((string)(this["ExitConditionRuleType_ToString"]));
            }
            set {
                this["ExitConditionRuleType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sequencing rules")]
        public string SequencingRulesType_ToString {
            get {
                return ((string)(this["SequencingRulesType_ToString"]));
            }
            set {
                this["SequencingRulesType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Organizations")]
        public string OrganizationsType_ToString {
            get {
                return ((string)(this["OrganizationsType_ToString"]));
            }
            set {
                this["OrganizationsType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources")]
        public string ResourcesType_ToString {
            get {
                return ((string)(this["ResourcesType_ToString"]));
            }
            set {
                this["ResourcesType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MetaData")]
        public string MetadataType_ToString {
            get {
                return ((string)(this["MetadataType_ToString"]));
            }
            set {
                this["MetadataType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rule Action")]
        public string ExitConditionRuleTypeRuleAction_ToString {
            get {
                return ((string)(this["ExitConditionRuleTypeRuleAction_ToString"]));
            }
            set {
                this["ExitConditionRuleTypeRuleAction_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Conditions")]
        public string SequencingRuleTypeRuleConditions_ToString {
            get {
                return ((string)(this["SequencingRuleTypeRuleConditions_ToString"]));
            }
            set {
                this["SequencingRuleTypeRuleConditions_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Conditon")]
        public string SequencingRuleTypeRuleConditionsRuleCondition_ToString {
            get {
                return ((string)(this["SequencingRuleTypeRuleConditionsRuleCondition_ToString"]));
            }
            set {
                this["SequencingRuleTypeRuleConditionsRuleCondition_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Conditions")]
        public string RollupRuleTypeRollupConditions_ToString {
            get {
                return ((string)(this["RollupRuleTypeRollupConditions_ToString"]));
            }
            set {
                this["RollupRuleTypeRollupConditions_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sequencing")]
        public string SequencingType_ToString {
            get {
                return ((string)(this["SequencingType_ToString"]));
            }
            set {
                this["SequencingType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Presentation")]
        public string PresentationType_ToString {
            get {
                return ((string)(this["PresentationType_ToString"]));
            }
            set {
                this["PresentationType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Randomization")]
        public string RandomizationType_ToString {
            get {
                return ((string)(this["RandomizationType_ToString"]));
            }
            set {
                this["RandomizationType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ffeditor@gmail.com")]
        public string SupportEMailAddress {
            get {
                return ((string)(this["SupportEMailAddress"]));
            }
            set {
                this["SupportEMailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Options_EnableLMSEmulation {
            get {
                return ((bool)(this["Options_EnableLMSEmulation"]));
            }
            set {
                this["Options_EnableLMSEmulation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control Mode")]
        public string ControlModeType_ToString {
            get {
                return ((string)(this["ControlModeType_ToString"]));
            }
            set {
                this["ControlModeType_ToString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New Theory")]
        public string DefaultTheoryItemTitle {
            get {
                return ((string)(this["DefaultTheoryItemTitle"]));
            }
            set {
                this["DefaultTheoryItemTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("New Examination")]
        public string DefaultQuestionItemTitle {
            get {
                return ((string)(this["DefaultQuestionItemTitle"]));
            }
            set {
                this["DefaultQuestionItemTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Summary")]
        public string DefaultSummaryItemTitle {
            get {
                return ((string)(this["DefaultSummaryItemTitle"]));
            }
            set {
                this["DefaultSummaryItemTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} - FireFly Course Editor r6")]
        public string MainFormCaptionFormat {
            get {
                return ((string)(this["MainFormCaptionFormat"]));
            }
            set {
                this["MainFormCaptionFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Options_PlainTextEnabled {
            get {
                return ((bool)(this["Options_PlainTextEnabled"]));
            }
            set {
                this["Options_PlainTextEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CourseDesigner_Visible {
            get {
                return ((bool)(this["CourseDesigner_Visible"]));
            }
            set {
                this["CourseDesigner_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("152, 190")]
        public global::System.Drawing.Point MainForm_Location {
            get {
                return ((global::System.Drawing.Point)(this["MainForm_Location"]));
            }
            set {
                this["MainForm_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("748, 631")]
        public global::System.Drawing.Size MainForm_Size {
            get {
                return ((global::System.Drawing.Size)(this["MainForm_Size"]));
            }
            set {
                this["MainForm_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"us-ascii\"?>\r\n<!--DockPanel configuration file. Auth" +
            "or: Weifen Luo, all rights reserved.-->\r\n<!--!!! AUTOMATICALLY GENERATED FILE. D" +
            "O NOT MODIFY !!!-->\r\n<DockPanel FormatVersion=\"1.0\" DockLeftPortion=\"0.25\" DockR" +
            "ightPortion=\"0.253420752565564\" DockTopPortion=\"0.25\" DockBottomPortion=\"0.25\" A" +
            "ctiveDocumentPane=\"0\" ActivePane=\"0\">\r\n  <Contents Count=\"4\">\r\n    <Content ID=\"" +
            "0\" PersistString=\"FireFly.CourseEditor.GUI.ManifestBrowser\" AutoHidePortion=\"0.2" +
            "5\" IsHidden=\"True\" IsFloat=\"True\" />\r\n    <Content ID=\"1\" PersistString=\"FireFly" +
            ".CourseEditor.GUI.PropertyEditor\" AutoHidePortion=\"0.25\" IsHidden=\"False\" IsFloa" +
            "t=\"False\" />\r\n    <Content ID=\"2\" PersistString=\"FireFly.CourseEditor.GUI.Course" +
            "Explorer\" AutoHidePortion=\"0.25\" IsHidden=\"False\" IsFloat=\"False\" />\r\n    <Conte" +
            "nt ID=\"3\" PersistString=\"FireFly.CourseEditor.GUI.CourseDesigner\" AutoHidePortio" +
            "n=\"0.25\" IsHidden=\"False\" IsFloat=\"False\" />\r\n  </Contents>\r\n  <Panes Count=\"3\">" +
            "\r\n    <Pane ID=\"0\" DockState=\"Document\" ActiveContent=\"3\">\r\n      <Contents Coun" +
            "t=\"3\">\r\n        <Content ID=\"0\" RefID=\"3\" />\r\n        <Content ID=\"1\" RefID=\"0\" " +
            "/>\r\n        <Content ID=\"2\" RefID=\"2\" />\r\n      </Contents>\r\n    </Pane>\r\n    <P" +
            "ane ID=\"1\" DockState=\"DockRight\" ActiveContent=\"1\">\r\n      <Contents Count=\"1\">\r" +
            "\n        <Content ID=\"0\" RefID=\"1\" />\r\n      </Contents>\r\n    </Pane>\r\n    <Pane" +
            " ID=\"2\" DockState=\"Float\" ActiveContent=\"-1\">\r\n      <Contents Count=\"1\">\r\n     " +
            "   <Content ID=\"0\" RefID=\"0\" />\r\n      </Contents>\r\n    </Pane>\r\n  </Panes>\r\n  <" +
            "DockWindows>\r\n    <DockWindow ID=\"0\" DockState=\"Document\" ZOrderIndex=\"0\">\r\n    " +
            "  <NestedPanes Count=\"1\">\r\n        <Pane ID=\"0\" RefID=\"0\" PrevPane=\"-1\" Alignmen" +
            "t=\"Right\" Proportion=\"0.5\" />\r\n      </NestedPanes>\r\n    </DockWindow>\r\n    <Doc" +
            "kWindow ID=\"1\" DockState=\"DockLeft\" ZOrderIndex=\"2\">\r\n      <NestedPanes Count=\"" +
            "0\" />\r\n    </DockWindow>\r\n    <DockWindow ID=\"2\" DockState=\"DockRight\" ZOrderInd" +
            "ex=\"1\">\r\n      <NestedPanes Count=\"1\">\r\n        <Pane ID=\"0\" RefID=\"1\" PrevPane=" +
            "\"-1\" Alignment=\"Bottom\" Proportion=\"0.5\" />\r\n      </NestedPanes>\r\n    </DockWin" +
            "dow>\r\n    <DockWindow ID=\"3\" DockState=\"DockTop\" ZOrderIndex=\"3\">\r\n      <Nested" +
            "Panes Count=\"0\" />\r\n    </DockWindow>\r\n    <DockWindow ID=\"4\" DockState=\"DockBot" +
            "tom\" ZOrderIndex=\"4\">\r\n      <NestedPanes Count=\"0\" />\r\n    </DockWindow>\r\n  </D" +
            "ockWindows>\r\n  <FloatWindows Count=\"1\">\r\n    <FloatWindow ID=\"0\" Bounds=\"320, 28" +
            "9, 300, 300\" ZOrderIndex=\"0\">\r\n      <NestedPanes Count=\"1\">\r\n        <Pane ID=\"" +
            "0\" RefID=\"2\" PrevPane=\"-1\" Alignment=\"Right\" Proportion=\"0.5\" />\r\n      </Nested" +
            "Panes>\r\n    </FloatWindow>\r\n  </FloatWindows>\r\n</DockPanel>")]
        public string DockingLayout {
            get {
                return ((string)(this["DockingLayout"]));
            }
            set {
                this["DockingLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("491, 2")]
        public string ManifestBrowser_Location {
            get {
                return ((string)(this["ManifestBrowser_Location"]));
            }
            set {
                this["ManifestBrowser_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("492, 350")]
        public string CourseExplorer_Location {
            get {
                return ((string)(this["CourseExplorer_Location"]));
            }
            set {
                this["CourseExplorer_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public string PropertyEditor_Location {
            get {
                return ((string)(this["PropertyEditor_Location"]));
            }
            set {
                this["PropertyEditor_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ManifestBrowser_Visible {
            get {
                return ((string)(this["ManifestBrowser_Visible"]));
            }
            set {
                this["ManifestBrowser_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string CourseExplorer_Visible {
            get {
                return ((string)(this["CourseExplorer_Visible"]));
            }
            set {
                this["CourseExplorer_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string PropertyEditor_Visible {
            get {
                return ((string)(this["PropertyEditor_Visible"]));
            }
            set {
                this["PropertyEditor_Visible"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string ManifestBrowser_WindowState {
            get {
                return ((string)(this["ManifestBrowser_WindowState"]));
            }
            set {
                this["ManifestBrowser_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string CourseExplorer_WindowState {
            get {
                return ((string)(this["CourseExplorer_WindowState"]));
            }
            set {
                this["CourseExplorer_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string PropertyEditor_WindowState {
            get {
                return ((string)(this["PropertyEditor_WindowState"]));
            }
            set {
                this["PropertyEditor_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 346")]
        public string ManifestBrowser_Size {
            get {
                return ((string)(this["ManifestBrowser_Size"]));
            }
            set {
                this["ManifestBrowser_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 187")]
        public string CourseExplorer_Size {
            get {
                return ((string)(this["CourseExplorer_Size"]));
            }
            set {
                this["CourseExplorer_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240, 370")]
        public string PropertyEditor_Size {
            get {
                return ((string)(this["PropertyEditor_Size"]));
            }
            set {
                this["PropertyEditor_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2, 2")]
        public string CourseDesigner_Location {
            get {
                return ((string)(this["CourseDesigner_Location"]));
            }
            set {
                this["CourseDesigner_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public string CourseDesigner_WindowState {
            get {
                return ((string)(this["CourseDesigner_WindowState"]));
            }
            set {
                this["CourseDesigner_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("487, 534")]
        public string CourseDesigner_Size {
            get {
                return ((string)(this["CourseDesigner_Size"]));
            }
            set {
                this["CourseDesigner_Size"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string SaveRestoreWindowsState {
            get {
                return ((string)(this["SaveRestoreWindowsState"]));
            }
            set {
                this["SaveRestoreWindowsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string ShowToolBar {
            get {
                return ((string)(this["ShowToolBar"]));
            }
            set {
                this["ShowToolBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastCourses {
            get {
                return ((string)(this["LastCourses"]));
            }
            set {
                this["LastCourses"] = value;
            }
        }
    }
}
