/*ALTER TABLE [dbo].[CurriculumChapterTopics]
    ADD CONSTRAINT [IX_CurriculumChapterTopics] UNIQUE NONCLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];*/

