ALTER TABLE [dbo].[CoursesInfo]
    ADD CONSTRAINT [PK_CoursesInfo] PRIMARY KEY CLUSTERED ([CourseId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

