ALTER TABLE [dbo].[UserRoles]
    ADD CONSTRAINT [PK_UserRoles] PRIMARY KEY CLUSTERED ([UserRef] ASC, [RoleRef] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

