ALTER TABLE [dbo].[UserScores]
    ADD CONSTRAINT [PK_UserScores] PRIMARY KEY CLUSTERED ([UserId] ASC, [TagId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

