ALTER TABLE tblUsers ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblSampleBusinesObject ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblGroups ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxSampleBusinesObjectOperation ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxThemeOperations ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxStageOperations ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxRoles ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxPageTypes ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxPageOrders ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxPageOperations ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxLanguages ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxCurriculumOperations ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxCourseOperations ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxCompiledStatuses ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblCurriculums ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblCourses ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblCompiledAnswers ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblCompiledQuestions ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblStages ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblThemes ADD sysState smallint not null DEFAULT 0
ALTER TABLE relStagesThemes ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblPermissions ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblPages ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblCompiledQuestionsData ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblQuestions ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblFiles ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblCompiledAnswersData ADD sysState smallint not null DEFAULT 0
ALTER TABLE tblUserAnswers ADD sysState smallint not null DEFAULT 0
ALTER TABLE relUserRoles ADD sysState smallint not null DEFAULT 0
ALTER TABLE relUserGroups ADD sysState smallint not null DEFAULT 0
ALTER TABLE fxGroupOperations ADD sysState smallint not null DEFAULT 0