<?xml version="1.0" encoding="utf-8"?><Database Name="IUDICO" Class="IUDICODataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=IUDICO;Integrated Security=True;Pooling=False" SettingsObjectName="IUDICO.Common.Properties.Settings" SettingsPropertyName="IUDICOConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Chapters" Member="Chapters">
    <Type Name="Chapter">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DisciplineRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Chapter_CurriculumChapter" Member="CurriculumChapters" ThisKey="Id" OtherKey="ChapterRef" Type="CurriculumChapter" />
      <Association Name="Chapter_Topic" Member="Topics" ThisKey="Id" OtherKey="ChapterRef" Type="Topic" />
      <Association Name="Discipline_Chapter" Member="Discipline" ThisKey="DisciplineRef" OtherKey="Id" Type="Discipline" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserTopicRatings" Member="UserTopicRatings">
    <Type Name="UserTopicRating">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TopicId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ChoiceQuestionsCorrectChoices" Member="ChoiceQuestionsCorrectChoices">
    <Type Name="ChoiceQuestionsCorrectChoice">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CorrectChoice" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="QuestionsInfo_ChoiceQuestionsCorrectChoice" Member="QuestionsInfo" ThisKey="QuestionId" OtherKey="Id" Type="QuestionsInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChoiceQuestionsOptions" Member="ChoiceQuestionsOptions">
    <Type Name="ChoiceQuestionsOption">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Option]" Member="Option" Type="System.String" DbType="NVarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="QuestionsInfo_ChoiceQuestionsOption" Member="QuestionsInfo" ThisKey="QuestionId" OtherKey="Id" Type="QuestionsInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompiledTestQuestions" Member="CompiledTestQuestions">
    <Type Name="CompiledTestQuestion">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TestNumber" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TestInput" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TestOutput" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="QuestionsInfo_CompiledTestQuestion" Member="QuestionsInfo" ThisKey="QuestionId" OtherKey="Id" Type="QuestionsInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Computers" Member="Computers">
    <Type Name="Computer">
      <Column Name="IpAddress" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Banned" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CurrentUser" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Courses" Member="Courses">
    <Type Name="Course">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Locked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Sequencing" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Course_CoursesInfo" Member="CoursesInfo" ThisKey="Id" OtherKey="CourseId" Type="CoursesInfo" Cardinality="One" />
      <Association Name="Course_CourseUser" Member="CourseUsers" ThisKey="Id" OtherKey="CourseRef" Type="CourseUser" />
      <Association Name="Course_Node" Member="Nodes" ThisKey="Id" OtherKey="CourseId" Type="Node" />
      <Association Name="Course_NodesInfo" Member="NodesInfos" ThisKey="Id" OtherKey="CourseId" Type="NodesInfo" />
      <Association Name="Course_StudyResult" Member="StudyResults" ThisKey="Id" OtherKey="CourseRef" Type="StudyResult" />
    </Type>
  </Table>
  <Table Name="dbo.CoursesInfo" Member="CoursesInfos">
    <Type Name="CoursesInfo">
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OverallMaxScore" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Course_CoursesInfo" Member="Course" ThisKey="CourseId" OtherKey="Id" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CourseUsers" Member="CourseUsers">
    <Type Name="CourseUser">
      <Column Name="CourseRef" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserRef" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Course_CourseUser" Member="Course" ThisKey="CourseRef" OtherKey="Id" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CurriculumChapters" Member="CurriculumChapters">
    <Type Name="CurriculumChapter">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurriculumRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChapterRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CurriculumChapter_CurriculumChapterTopic" Member="CurriculumChapterTopics" ThisKey="Id" OtherKey="CurriculumChapterRef" Type="CurriculumChapterTopic" />
      <Association Name="Chapter_CurriculumChapter" Member="Chapter" ThisKey="ChapterRef" OtherKey="Id" Type="Chapter" IsForeignKey="true" />
      <Association Name="Curriculum_CurriculumChapter" Member="Curriculum" ThisKey="CurriculumRef" OtherKey="Id" Type="Curriculum" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CurriculumChapterTopics" Member="CurriculumChapterTopics">
    <Type Name="CurriculumChapterTopic">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurriculumChapterRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TopicRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TestEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TheoryStartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TheoryEndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThresholdOfSuccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BlockTopicAtTesting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="BlockCurriculumAtTesting" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="CurriculumChapter_CurriculumChapterTopic" Member="CurriculumChapter" ThisKey="CurriculumChapterRef" OtherKey="Id" Type="CurriculumChapter" IsForeignKey="true" />
      <Association Name="Topic_CurriculumChapterTopic" Member="Topic" ThisKey="TopicRef" OtherKey="Id" Type="Topic" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Curriculums" Member="Curriculums">
    <Type Name="Curriculum">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserGroupRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisciplineRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsValid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Curriculum_CurriculumChapter" Member="CurriculumChapters" ThisKey="Id" OtherKey="CurriculumRef" Type="CurriculumChapter" />
      <Association Name="Discipline_Curriculum" Member="Discipline" ThisKey="DisciplineRef" OtherKey="Id" Type="Discipline" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Disciplines" Member="Disciplines">
    <Type Name="Discipline">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Owner" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsValid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Discipline_Chapter" Member="Chapters" ThisKey="Id" OtherKey="DisciplineRef" Type="Chapter" />
      <Association Name="Discipline_Curriculum" Member="Curriculums" ThisKey="Id" OtherKey="DisciplineRef" Type="Curriculum" />
      <Association Name="Discipline_SharedDiscipline" Member="SharedDisciplines" ThisKey="Id" OtherKey="DisciplineRef" Type="SharedDiscipline" />
    </Type>
  </Table>
  <Table Name="dbo.ForecastingResults" Member="ForecastingResults">
    <Type Name="ForecastingResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentRef" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="TreeRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ForecastingPoint" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ForecastingPercent" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="ForecastingTree_ForecastingResult" Member="ForecastingTree" ThisKey="TreeRef" OtherKey="Id" Type="ForecastingTree" IsForeignKey="true" />
      <Association Name="User_ForecastingResult" Member="User" ThisKey="StudentRef" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ForecastingTree" Member="ForecastingTrees">
    <Type Name="ForecastingTree">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserRef" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ForecastingTree_ForecastingResult" Member="ForecastingResults" ThisKey="Id" OtherKey="TreeRef" Type="ForecastingResult" />
      <Association Name="ForecastingTree_ForecastingTreeGroup" Member="ForecastingTreeGroups" ThisKey="Id" OtherKey="TreeRef" Type="ForecastingTreeGroup" />
      <Association Name="ForecastingTree_ForecastingTreeNode" Member="ForecastingTreeNodes" ThisKey="Id" OtherKey="TreeRef" Type="ForecastingTreeNode" />
    </Type>
  </Table>
  <Table Name="dbo.ForecastingTreeGroups" Member="ForecastingTreeGroups">
    <Type Name="ForecastingTreeGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TreeRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GroupRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ForecastingTree_ForecastingTreeGroup" Member="ForecastingTree" ThisKey="TreeRef" OtherKey="Id" Type="ForecastingTree" IsForeignKey="true" />
      <Association Name="Group_ForecastingTreeGroup" Member="Group" ThisKey="GroupRef" OtherKey="Id" Type="Group" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ForecastingTreeNode" Member="ForecastingTreeNodes">
    <Type Name="ForecastingTreeNode">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TreeRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CourseRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ForecastingTreeNode_ForecastingTreeNode" Member="ForecastingTreeNodes" ThisKey="Id" OtherKey="ParentRef" Type="ForecastingTreeNode" />
      <Association Name="ForecastingTree_ForecastingTreeNode" Member="ForecastingTree" ThisKey="TreeRef" OtherKey="Id" Type="ForecastingTree" IsForeignKey="true" />
      <Association Name="ForecastingTreeNode_ForecastingTreeNode" Member="ForecastingTreeNode1" ThisKey="ParentRef" OtherKey="Id" Type="ForecastingTreeNode" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Group]" Member="Groups">
    <Type Name="Group">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Group_ForecastingTreeGroup" Member="ForecastingTreeGroups" ThisKey="Id" OtherKey="GroupRef" Type="ForecastingTreeGroup" />
      <Association Name="Group_GroupUser" Member="GroupUsers" ThisKey="Id" OtherKey="GroupRef" Type="GroupUser" />
    </Type>
  </Table>
  <Table Name="dbo.GroupUsers" Member="GroupUsers">
    <Type Name="GroupUser">
      <Column Name="GroupRef" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserRef" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Group_GroupUser" Member="Group" ThisKey="GroupRef" OtherKey="Id" Type="Group" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="User_GroupUser" Member="User" ThisKey="UserRef" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NodeResources" Member="NodeResources">
    <Type Name="NodeResource">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NodeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Node_NodeResource" Member="Node" ThisKey="NodeId" OtherKey="Id" Type="Node" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Nodes" Member="Nodes">
    <Type Name="Node">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsFolder" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Position" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Sequencing" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Node_NodeResource" Member="NodeResources" ThisKey="Id" OtherKey="NodeId" Type="NodeResource" />
      <Association Name="Node_Node" Member="Nodes" ThisKey="Id" OtherKey="ParentId" Type="Node" />
      <Association Name="Course_Node" Member="Course" ThisKey="CourseId" OtherKey="Id" Type="Course" IsForeignKey="true" />
      <Association Name="Node_Node" Member="Node1" ThisKey="ParentId" OtherKey="Id" Type="Node" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NodesInfo" Member="NodesInfos">
    <Type Name="NodesInfo">
      <Column Name="NodeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaxScore" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="NodesInfo_QuestionsInfo" Member="QuestionsInfos" ThisKey="NodeId" OtherKey="NodeId" Type="QuestionsInfo" />
      <Association Name="Course_NodesInfo" Member="Course" ThisKey="CourseId" OtherKey="Id" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionsInfo" Member="QuestionsInfos">
    <Type Name="QuestionsInfo">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NodeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="MaxScore" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QuestionsInfo_ChoiceQuestionsCorrectChoice" Member="ChoiceQuestionsCorrectChoice" ThisKey="Id" OtherKey="QuestionId" Type="ChoiceQuestionsCorrectChoice" Cardinality="One" />
      <Association Name="QuestionsInfo_ChoiceQuestionsOption" Member="ChoiceQuestionsOptions" ThisKey="Id" OtherKey="QuestionId" Type="ChoiceQuestionsOption" />
      <Association Name="QuestionsInfo_CompiledTestQuestion" Member="CompiledTestQuestions" ThisKey="Id" OtherKey="QuestionId" Type="CompiledTestQuestion" />
      <Association Name="QuestionsInfo_SimpleQuestion" Member="SimpleQuestion" ThisKey="Id" OtherKey="QuestionId" Type="SimpleQuestion" Cardinality="One" />
      <Association Name="NodesInfo_QuestionsInfo" Member="NodesInfo" ThisKey="NodeId" OtherKey="NodeId" Type="NodesInfo" IsForeignKey="true" />
      <Association Name="QuestionType_QuestionsInfo" Member="QuestionType" ThisKey="Type" OtherKey="Type" Type="QuestionType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuestionTypes" Member="QuestionTypes">
    <Type Name="QuestionType">
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Association Name="QuestionType_QuestionsInfo" Member="QuestionsInfos" ThisKey="Type" OtherKey="Type" Type="QuestionsInfo" />
    </Type>
  </Table>
  <Table Name="dbo.Rooms" Member="Rooms">
    <Type Name="Room">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Allowed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SharedDisciplines" Member="SharedDisciplines">
    <Type Name="SharedDiscipline">
      <Column Name="DisciplineRef" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserRef" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Discipline_SharedDiscipline" Member="Discipline" ThisKey="DisciplineRef" OtherKey="Id" Type="Discipline" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SimpleQuestions" Member="SimpleQuestions">
    <Type Name="SimpleQuestion">
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CorrectAnswer" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="QuestionsInfo_SimpleQuestion" Member="QuestionsInfo" ThisKey="QuestionId" OtherKey="Id" Type="QuestionsInfo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudyResults" Member="StudyResults">
    <Type Name="StudyResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StudentRef" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CourseRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Point" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_StudyResult" Member="Course" ThisKey="CourseRef" OtherKey="Id" Type="Course" IsForeignKey="true" />
      <Association Name="User_StudyResult" Member="User" ThisKey="StudentRef" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Tag_TopicScore" Member="TopicScores" ThisKey="Id" OtherKey="TagId" Type="TopicScore" />
      <Association Name="Tag_TopicTag" Member="TopicTags" ThisKey="Id" OtherKey="TagId" Type="TopicTag" />
      <Association Name="Tag_UserScore" Member="UserScores" ThisKey="Id" OtherKey="TagId" Type="UserScore" />
    </Type>
  </Table>
  <Table Name="dbo.Topics" Member="Topics">
    <Type Name="Topic">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ChapterRef" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestCourseRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TestTopicTypeRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TheoryCourseRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TheoryTopicTypeRef" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Updated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Topic_CurriculumChapterTopic" Member="CurriculumChapterTopics" ThisKey="Id" OtherKey="TopicRef" Type="CurriculumChapterTopic" />
      <Association Name="Chapter_Topic" Member="Chapter" ThisKey="ChapterRef" OtherKey="Id" Type="Chapter" IsForeignKey="true" />
      <Association Name="TopicType_Topic" Member="TopicType" ThisKey="TestTopicTypeRef" OtherKey="Id" Type="TopicType" IsForeignKey="true" />
      <Association Name="TopicType_Topic1" Member="TopicType1" ThisKey="TheoryTopicTypeRef" OtherKey="Id" Type="TopicType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TopicScores" Member="TopicScores">
    <Type Name="TopicScore">
      <Column Name="TopicId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Score" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Tag_TopicScore" Member="Tag" ThisKey="TagId" OtherKey="Id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TopicTags" Member="TopicTags">
    <Type Name="TopicTag">
      <Column Name="TopicId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Tag_TopicTag" Member="Tag" ThisKey="TagId" OtherKey="Id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TopicTypes" Member="TopicTypes">
    <Type Name="TopicType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TopicType_Topic" Member="Topics" ThisKey="Id" OtherKey="TestTopicTypeRef" Type="Topic" />
      <Association Name="TopicType_Topic1" Member="Topics1" ThisKey="Id" OtherKey="TheoryTopicTypeRef" Type="Topic" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="OpenId" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="IsApproved" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ApprovedBy" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="TestsSum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TestsTotal" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_ForecastingResult" Member="ForecastingResults" ThisKey="Id" OtherKey="StudentRef" Type="ForecastingResult" />
      <Association Name="User_GroupUser" Member="GroupUsers" ThisKey="Id" OtherKey="UserRef" Type="GroupUser" />
      <Association Name="User_StudyResult" Member="StudyResults" ThisKey="Id" OtherKey="StudentRef" Type="StudyResult" />
      <Association Name="User_User" Member="Users" ThisKey="Id" OtherKey="ApprovedBy" Type="User" />
      <Association Name="User_UserRole" Member="UserRoles" ThisKey="Id" OtherKey="UserRef" Type="UserRole" />
      <Association Name="User_User" Member="User1" ThisKey="ApprovedBy" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserActivities" Member="UserActivities">
    <Type Name="UserActivity">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserRef" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="RequestStartTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RequestEndTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="RequestLength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ResponseLength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Request" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserRoles" Member="UserRoles">
    <Type Name="UserRole">
      <Column Name="UserRef" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleRef" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="User_UserRole" Member="User" ThisKey="UserRef" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserScores" Member="UserScores">
    <Type Name="UserScore">
      <Column Name="UserId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TagId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Score" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Association Name="Tag_UserScore" Member="Tag" ThisKey="TagId" OtherKey="Id" Type="Tag" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RoomAttachments" Member="RoomAttachments">
    <Type Name="RoomAttachment">
      <Column Name="RoomRef" Member="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ComputerRef" Member="ComputerIp" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
</Database>