ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [IUDICO], FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQL2008R2\MSSQL\DATA\IUDICO.mdf', SIZE = 13568 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];

