/*ALTER DATABASE [$(DatabaseName)]
    ADD FILE (NAME = [IUDICO], FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\IUDICO.mdf', SIZE = 2304 KB, FILEGROWTH = 1024 KB) TO FILEGROUP [PRIMARY];
    */
