ALTER TABLE [dbo].[CourseUsers]
    ADD CONSTRAINT [PK_CourseUsers] PRIMARY KEY CLUSTERED ([CourseRef] ASC, [UserRef] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

