//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatisRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Statistics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Statistics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IUDICO.Statistics.Statistics", typeof(Statistics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt statistic:.
        /// </summary>
        public static string AttemptStatistic {
            get {
                return ResourceManager.GetString("AttemptStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison.
        /// </summary>
        public static string Comparison {
            get {
                return ResourceManager.GetString("Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corect Answer.
        /// </summary>
        public static string CorectAnswer {
            get {
                return ResourceManager.GetString("CorectAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum list.
        /// </summary>
        public static string CurriculumList {
            get {
                return ResourceManager.GetString("CurriculumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum name.
        /// </summary>
        public static string CurriculumName {
            get {
                return ResourceManager.GetString("CurriculumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculums statistic for group.
        /// </summary>
        public static string CurriculumsStatisticForGroup {
            get {
                return ResourceManager.GetString("CurriculumsStatisticForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group list.
        /// </summary>
        public static string GroupList {
            get {
                return ResourceManager.GetString("GroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of question.
        /// </summary>
        public static string NumberOfQuestion {
            get {
                return ResourceManager.GetString("NumberOfQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resaults.
        /// </summary>
        public static string Resaults {
            get {
                return ResourceManager.GetString("Resaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select attempt to show:.
        /// </summary>
        public static string SelectAttempt {
            get {
                return ResourceManager.GetString("SelectAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select one or more curriculum :.
        /// </summary>
        public static string SelectCurriculum {
            get {
                return ResourceManager.GetString("SelectCurriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select one curriculum :.
        /// </summary>
        public static string SelectOneCurriculum {
            get {
                return ResourceManager.GetString("SelectOneCurriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select one group :.
        /// </summary>
        public static string SelectOneGroup {
            get {
                return ResourceManager.GetString("SelectOneGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Answer.
        /// </summary>
        public static string StudentAnswer {
            get {
                return ResourceManager.GetString("StudentAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
    }
}
