DROP PROCEDURE [spCompiledQuestionsInsert]
DROP PROCEDURE [spCompiledQuestionsDataInsert]
DROP PROCEDURE [spThemesInsert]
DROP PROCEDURE [spPagesInsert]
DROP PROCEDURE [spFilesInsert]
DROP PROCEDURE [spCoursesInsert]
DROP PROCEDURE [spUserAnswersInsert]
DROP PROCEDURE [spQuestionsInsert]