ALTER TABLE [dbo].[GroupUsers]
    ADD CONSTRAINT [PK_GroupUsers] PRIMARY KEY CLUSTERED ([GroupRef] ASC, [UserRef] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

