//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IUDICO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurriculumAssignment
    {
        public CurriculumAssignment()
        {
            this.ThemeAssignments = new HashSet<ThemeAssignment>();
            this.Timelines = new HashSet<Timeline>();
        }
    
        public int Id { get; set; }
        public int UserGroupRef { get; set; }
        public int CurriculumRef { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Curriculum Curriculum { get; set; }
        public virtual ICollection<ThemeAssignment> ThemeAssignments { get; set; }
        public virtual ICollection<Timeline> Timelines { get; set; }
    }
}
