ALTER TABLE [dbo].[TopicTags]
    ADD CONSTRAINT [PK_TopicFeatures] PRIMARY KEY CLUSTERED ([TopicId] ASC, [TagId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

