ALTER TABLE [dbo].[CompiledTestQuestions]
    ADD CONSTRAINT [PK_CompiledTestQuestions] PRIMARY KEY CLUSTERED ([QuestionId] ASC, [TestNumber] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

