ALTER TABLE [dbo].[SharedDisciplines]
    ADD CONSTRAINT [PK_SharedDisciplines_1] PRIMARY KEY CLUSTERED ([DisciplineRef] ASC, [UserRef] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

