ALTER TABLE [dbo].[UserTopicScores]
    ADD CONSTRAINT [PK_UserTopicScores] PRIMARY KEY CLUSTERED ([UserId] ASC, [TopicId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

