ALTER TABLE [dbo].[User]
    ADD CONSTRAINT [UQ__User__536C85E4182C9B23] UNIQUE NONCLUSTERED ([Username] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

