//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IUDICO.DataModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IUDICO.DataModel.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a number.
        /// </summary>
        internal static string Admin_CreateBulkUserController_DoCreate__0__is_not_a_number {
            get {
                return ResourceManager.GetString("Admin_CreateBulkUserController_DoCreate__0__is_not_a_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group name is empty.
        /// </summary>
        internal static string Admin_CreateBulkUserController_DoCreate_Group_name_is_empty {
            get {
                return ResourceManager.GetString("Admin_CreateBulkUserController_DoCreate_Group_name_is_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not specified.
        /// </summary>
        internal static string Admin_CreateBulkUserController_DoCreate_Password_is_not_specified {
            get {
                return ResourceManager.GetString("Admin_CreateBulkUserController_DoCreate_Password_is_not_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of users like these already exist.
        /// </summary>
        internal static string Admin_CreateBulkUserController_DoCreate_Some_of_users_like_these_already_exist {
            get {
                return ResourceManager.GetString("Admin_CreateBulkUserController_DoCreate_Some_of_users_like_these_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating setting - possibly setting with such name already exists.
        /// </summary>
        internal static string Admin_CreateSettingController_CreateSetting_Error_creating_setting___possibly_setting_with_such_name_already_exists {
            get {
                return ResourceManager.GetString("Admin_CreateSettingController_CreateSetting_Error_creating_setting___possibly_set" +
                        "ting_with_such_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        internal static string Admin_SearchPageSolrController_Button1_Click_No_data_found {
            get {
                return ResourceManager.GetString("Admin_SearchPageSolrController_Button1_Click_No_data_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object {0} with ID {1} not found in the Cache.
        /// </summary>
        internal static string CacheUtility_Get_Object__0__with_ID__1__not_found_in_the_Cache {
            get {
                return ResourceManager.GetString("CacheUtility_Get_Object__0__with_ID__1__not_found_in_the_Cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is not supported.
        /// </summary>
        internal static string CmiDataModel_GetCollection_Requested_variable_is_not_supported {
            get {
                return ResourceManager.GetString("CmiDataModel_GetCollection_Requested_variable_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is write-only.
        /// </summary>
        internal static string CmiDataModel_GetVariable_Requested_variable_is_write_only {
            get {
                return ResourceManager.GetString("CmiDataModel_GetVariable_Requested_variable_is_write_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is read-only.
        /// </summary>
        internal static string CmiDataModel_SetValue_Requested_variable_is_read_only {
            get {
                return ResourceManager.GetString("CmiDataModel_SetValue_Requested_variable_is_read_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding is not allowed.
        /// </summary>
        internal static string ControlledPage_CheckBindingAllowed_Binding_is_not_allowed {
            get {
                return ResourceManager.GetString("ControlledPage_CheckBindingAllowed_Binding_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already redirected.
        /// </summary>
        internal static string ControllerBase_RedirectToController_Already_redirected {
            get {
                return ResourceManager.GetString("ControllerBase_RedirectToController_Already_redirected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} cannot be specified for controller parameter.
        /// </summary>
        internal static string ControllerParametersUtility_ControllerParametersUtility_Type__0__cannot_be_specified_for_controller_parameter {
            get {
                return ResourceManager.GetString("ControllerParametersUtility_ControllerParametersUtility_Type__0__cannot_be_specif" +
                        "ied_for_controller_parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page you can change behavior of course organizations.
        /// </summary>
        internal static string CourseBehaviorController_PageLoad_On_this_page_you_can_change_behavior_of_course_organizations {
            get {
                return ResourceManager.GetString("CourseBehaviorController_PageLoad_On_this_page_you_can_change_behavior_of_course_" +
                        "organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Preferences is saved.
        /// </summary>
        internal static string CourseBehaviorController_SaveButtonClick_You_Preferences_is_saved {
            get {
                return ResourceManager.GetString("CourseBehaviorController_SaveButtonClick_You_Preferences_is_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string CourseDeleteConfirmationController_GetDependencies_by {
            get {
                return ResourceManager.GetString("CourseDeleteConfirmationController_GetDependencies_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is used in Curriculum.
        /// </summary>
        internal static string CourseDeleteConfirmationController_GetDependencies_is_used_in_Curriculum {
            get {
                return ResourceManager.GetString("CourseDeleteConfirmationController_GetDependencies_is_used_in_Curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string CourseDeleteConfirmationController_GetDependencies_Theme {
            get {
                return ResourceManager.GetString("CourseDeleteConfirmationController_GetDependencies_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        internal static string CourseDeleteConfirmationController_noneMessage_None_ {
            get {
                return ResourceManager.GetString("CourseDeleteConfirmationController_noneMessage_None_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting course: {0}..
        /// </summary>
        internal static string CourseDeleteConfirmationController_pageCaption_Deleting_course___0__ {
            get {
                return ResourceManager.GetString("CourseDeleteConfirmationController_pageCaption_Deleting_course___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to delete course: {0}. This course is used in next objects:.
        /// </summary>
        internal static string CourseDeleteConfirmationController_pageDescription_You_want_to_delete_course___0___This_course_is_used_in_next_objects_ {
            get {
                return ResourceManager.GetString("CourseDeleteConfirmationController_pageDescription_You_want_to_delete_course___0_" +
                        "__This_course_is_used_in_next_objects_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify course path..
        /// </summary>
        internal static string CourseEditController_fileNotFound_Specify_course_path_ {
            get {
                return ResourceManager.GetString("CourseEditController_fileNotFound_Specify_course_path_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course management..
        /// </summary>
        internal static string CourseEditController_pageCaption_Course_management_ {
            get {
                return ResourceManager.GetString("CourseEditController_pageCaption_Course_management_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is course upload page. Please selected course, specify name and description and upload it..
        /// </summary>
        internal static string CourseEditController_pageDescription_This_is_course_upload_page__Please_selected_course__specify_name_and_description_and_upload_it_ {
            get {
                return ResourceManager.GetString("CourseEditController_pageDescription_This_is_course_upload_page__Please_selected_" +
                        "course__specify_name_and_description_and_upload_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred during course upload..
        /// </summary>
        internal static string CourseEditController_uploadError_Error_occurred_during_course_upload_ {
            get {
                return ResourceManager.GetString("CourseEditController_uploadError_Error_occurred_during_course_upload_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course was uploaded successfully..
        /// </summary>
        internal static string CourseEditController_uploadSucces_Course_was_uploaded_successfully_ {
            get {
                return ResourceManager.GetString("CourseEditController_uploadSucces_Course_was_uploaded_successfully_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answers.xml file found.
        /// </summary>
        internal static string CourseManager_Import_No_answers_xml_file_found {
            get {
                return ResourceManager.GetString("CourseManager_Import_No_answers_xml_file_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No imsmanifest.xml file found.
        /// </summary>
        internal static string CourseManager_Import_No_imsmanifest_xml_file_found {
            get {
                return ResourceManager.GetString("CourseManager_Import_No_imsmanifest_xml_file_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have neither groups nor curriculums to assign. Create some first..
        /// </summary>
        internal static string CurriculumAssignmentController_neitherCurriculumsNorGroup_You_have_neither_groups_nor_curriculums_to_assign__Create_some_first_ {
            get {
                return ResourceManager.GetString("CurriculumAssignmentController_neitherCurriculumsNorGroup_You_have_neither_groups" +
                        "_nor_curriculums_to_assign__Create_some_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no curriculums to assign. Create some first..
        /// </summary>
        internal static string CurriculumAssignmentController_noCurriculums_You_have_no_curriculums_to_assign__Create_some_first_ {
            get {
                return ResourceManager.GetString("CurriculumAssignmentController_noCurriculums_You_have_no_curriculums_to_assign__C" +
                        "reate_some_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no groups to assign. Create some first..
        /// </summary>
        internal static string CurriculumAssignmentController_noGroups_You_have_no_groups_to_assign__Create_some_first_ {
            get {
                return ResourceManager.GetString("CurriculumAssignmentController_noGroups_You_have_no_groups_to_assign__Create_some" +
                        "_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum assignment..
        /// </summary>
        internal static string CurriculumAssignmentController_pageCaption_Curriculum_assignment_ {
            get {
                return ResourceManager.GetString("CurriculumAssignmentController_pageCaption_Curriculum_assignment_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is curriculum assignment page. Select group and curriculum to assign..
        /// </summary>
        internal static string CurriculumAssignmentController_pageDescription_This_is_curriculum_assignment_page__Select_group_and_curriculum_to_assign_ {
            get {
                return ResourceManager.GetString("CurriculumAssignmentController_pageDescription_This_is_curriculum_assignment_page" +
                        "__Select_group_and_curriculum_to_assign_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curriculum.
        /// </summary>
        internal static string CurriculumDeleteConfirmationController_curriculumStr_curriculum {
            get {
                return ResourceManager.GetString("CurriculumDeleteConfirmationController_curriculumStr_curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        internal static string CurriculumDeleteConfirmationController_noneMessage_None_ {
            get {
                return ResourceManager.GetString("CurriculumDeleteConfirmationController_noneMessage_None_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting {0}: {1}.
        /// </summary>
        internal static string CurriculumDeleteConfirmationController_pageCaption_Deleting__0____1_ {
            get {
                return ResourceManager.GetString("CurriculumDeleteConfirmationController_pageCaption_Deleting__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to delete {1}: {2}{3}, which is assigned to next groups:.
        /// </summary>
        internal static string CurriculumDeleteConfirmationController_pageDescription_You_want_to_delete__1____2__3___which_is_assigned_to_next_groups_ {
            get {
                return ResourceManager.GetString("CurriculumDeleteConfirmationController_pageDescription_You_want_to_delete__1____2" +
                        "__3___which_is_assigned_to_next_groups_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stage.
        /// </summary>
        internal static string CurriculumDeleteConfirmationController_stageStr_stage {
            get {
                return ResourceManager.GetString("CurriculumDeleteConfirmationController_stageStr_stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theme.
        /// </summary>
        internal static string CurriculumDeleteConfirmationController_themeStr_theme {
            get {
                return ResourceManager.GetString("CurriculumDeleteConfirmationController_themeStr_theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . It is used in curriculum {0}.
        /// </summary>
        internal static string CurriculumDeleteConfirmationController_usedInCurriculum___It_is_used_in_curriculum__0_ {
            get {
                return ResourceManager.GetString("CurriculumDeleteConfirmationController_usedInCurriculum___It_is_used_in_curriculu" +
                        "m__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage: {0} already contains theme(s) :.
        /// </summary>
        internal static string CurriculumEditController_alreadyHaveTheme_Stage___0__already_contains_theme_s___ {
            get {
                return ResourceManager.GetString("CurriculumEditController_alreadyHaveTheme_Stage___0__already_contains_theme_s___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no courses, upload some first..
        /// </summary>
        internal static string CurriculumEditController_noCourses_You_have_no_courses__upload_some_first_ {
            get {
                return ResourceManager.GetString("CurriculumEditController_noCourses_You_have_no_courses__upload_some_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name..
        /// </summary>
        internal static string CurriculumEditController_noName_Please_enter_the_name_ {
            get {
                return ResourceManager.GetString("CurriculumEditController_noName_Please_enter_the_name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter stage name.
        /// </summary>
        internal static string CurriculumEditController_noStageName_Please_enter_stage_name {
            get {
                return ResourceManager.GetString("CurriculumEditController_noStageName_Please_enter_stage_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select some themes to add..
        /// </summary>
        internal static string CurriculumEditController_noThemesSelected_Select_some_themes_to_add_ {
            get {
                return ResourceManager.GetString("CurriculumEditController_noThemesSelected_Select_some_themes_to_add_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum management..
        /// </summary>
        internal static string CurriculumEditController_pageCaption_Curriculum_management_ {
            get {
                return ResourceManager.GetString("CurriculumEditController_pageCaption_Curriculum_management_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is curriculum edit page page. Create/Edit/Delete your curriculum here..
        /// </summary>
        internal static string CurriculumEditController_pageDescription_This_is_curriculum_edit_page_page__Create_Edit_Delete_your_curriculum_here_ {
            get {
                return ResourceManager.GetString("CurriculumEditController_pageDescription_This_is_curriculum_edit_page_page__Creat" +
                        "e_Edit_Delete_your_curriculum_here_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline for group: {0} and curriculum: {1}.
        /// </summary>
        internal static string CurriculumTimelineController_pageCaption_Timeline_for_group___0__and_curriculum___1_ {
            get {
                return ResourceManager.GetString("CurriculumTimelineController_pageCaption_Timeline_for_group___0__and_curriculum__" +
                        "_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is detailed timeline for group: {0} and curriculum: {1}. You can manage group operations here..
        /// </summary>
        internal static string CurriculumTimelineController_pageDescription_This_is_detailed_timeline_for_group___0__and_curriculum___1___You_can_manage_group_operations_here_ {
            get {
                return ResourceManager.GetString("CurriculumTimelineController_pageDescription_This_is_detailed_timeline_for_group_" +
                        "__0__and_curriculum___1___You_can_manage_group_operations_here_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing ApplicationName is not allowed.
        /// </summary>
        internal static string CustomMembershipProvider_ApplicationName_Changing_ApplicationName_is_not_allowed {
            get {
                return ResourceManager.GetString("CustomMembershipProvider_ApplicationName_Changing_ApplicationName_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cann&apos;t change password of another user.
        /// </summary>
        internal static string CustomMembershipProvider_ChangePassword_You_cann_t_change_password_of_another_user {
            get {
                return ResourceManager.GetString("CustomMembershipProvider_ChangePassword_You_cann_t_change_password_of_another_use" +
                        "r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPassword is not allowed.
        /// </summary>
        internal static string CustomMembershipProvider_GetPassword_GetPassword_is_not_allowed {
            get {
                return ResourceManager.GetString("CustomMembershipProvider_GetPassword_GetPassword_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing ApplicationName is not allowed.
        /// </summary>
        internal static string CustomRoleProvider_ApplicationName_Changing_ApplicationName_is_not_allowed {
            get {
                return ResourceManager.GetString("CustomRoleProvider_ApplicationName_Changing_ApplicationName_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateRole is not allowed.
        /// </summary>
        internal static string CustomRoleProvider_CreateRole_CreateRole_is_not_allowed {
            get {
                return ResourceManager.GetString("CustomRoleProvider_CreateRole_CreateRole_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRole is not allowed.
        /// </summary>
        internal static string CustomRoleProvider_DeleteRole_DeleteRole_is_not_allowed {
            get {
                return ResourceManager.GetString("CustomRoleProvider_DeleteRole_DeleteRole_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPassword is not available.
        /// </summary>
        internal static string CustomUser_GetPassword_GetPassword_is_not_available {
            get {
                return ResourceManager.GetString("CustomUser_GetPassword_GetPassword_is_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Fx&apos; method is not initialized.
        /// </summary>
        internal static string DatabaseModel_DatabaseModel__Fx__method_is_not_initialized {
            get {
                return ResourceManager.GetString("DatabaseModel_DatabaseModel__Fx__method_is_not_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Load List&apos; method is not initialized.
        /// </summary>
        internal static string DatabaseModel_DatabaseModel__Load_List__method_is_not_initialized {
            get {
                return ResourceManager.GetString("DatabaseModel_DatabaseModel__Load_List__method_is_not_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;Query&apos; method.
        /// </summary>
        internal static string DatabaseModel_DatabaseModel_Unable_to_find__Query__method {
            get {
                return ResourceManager.GetString("DatabaseModel_DatabaseModel_Unable_to_find__Query__method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Delete method.
        /// </summary>
        internal static string DatabaseModel_DatabaseModel_Unable_to_find_Delete_method {
            get {
                return ResourceManager.GetString("DatabaseModel_DatabaseModel_Unable_to_find_Delete_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find Load method.
        /// </summary>
        internal static string DatabaseModel_DatabaseModel_Unable_to_find_Load_method {
            get {
                return ResourceManager.GetString("DatabaseModel_DatabaseModel_Unable_to_find_Load_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing .
        /// </summary>
        internal static string DatabaseModel_Delete_Removing_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Delete_Removing_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing multiple .
        /// </summary>
        internal static string DatabaseModel_Delete_Removing_multiple_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Delete_Removing_multiple_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} cannot take participation into many-to-many relationship because it is not derived from {1}.
        /// </summary>
        internal static string DatabaseModel_Initialize_Class__0__cannot_take_participation_into_many_to_many_relationship_because_it_is_not_derived_from__1_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Initialize_Class__0__cannot_take_participation_into_many_to_many_re" +
                        "lationship_because_it_is_not_derived_from__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} cannot take participation into many-to-many relationship because it is not marked with {1}.
        /// </summary>
        internal static string DatabaseModel_Initialize_Class__0__cannot_take_participation_into_many_to_many_relationship_because_it_is_not_marked_with__1_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Initialize_Class__0__cannot_take_participation_into_many_to_many_re" +
                        "lationship_because_it_is_not_marked_with__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Database Model....
        /// </summary>
        internal static string DatabaseModel_Initialize_Initializing_Database_Model___ {
            get {
                return ResourceManager.GetString("DatabaseModel_Initialize_Initializing_Database_Model___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Count = .
        /// </summary>
        internal static string DatabaseModel_Insert_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Insert_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataObject has been already inserted..
        /// </summary>
        internal static string DatabaseModel_Insert_DataObject_has_been_already_inserted_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Insert_DataObject_has_been_already_inserted_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting .
        /// </summary>
        internal static string DatabaseModel_Insert_Inserting_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Insert_Inserting_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting multiple .
        /// </summary>
        internal static string DatabaseModel_Insert_Inserting_multiple_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Insert_Inserting_multiple_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data Reader.
        /// </summary>
        internal static string DatabaseModel_Insert_Invalid_Data_Reader {
            get {
                return ResourceManager.GetString("DatabaseModel_Insert_Invalid_Data_Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of populated objects ({0}) lower than requested to extract {1}.
        /// </summary>
        internal static string DatabaseModel_Load_Count_of_populated_objects___0___lower_than_requested_to_extract__1_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Load_Count_of_populated_objects___0___lower_than_requested_to_extra" +
                        "ct__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got from cache.
        /// </summary>
        internal static string DatabaseModel_Load_Got_from_cache {
            get {
                return ResourceManager.GetString("DatabaseModel_Load_Got_from_cache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid object ID: {0}.
        /// </summary>
        internal static string DatabaseModel_Load_Invalid_object_ID___0_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Load_Invalid_object_ID___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading .
        /// </summary>
        internal static string DatabaseModel_Load_Loading_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Load_Loading_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading multiple .
        /// </summary>
        internal static string DatabaseModel_Load_Loading_multiple_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Load_Loading_multiple_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running sql....
        /// </summary>
        internal static string DatabaseModel_Load_Running_sql___ {
            get {
                return ResourceManager.GetString("DatabaseModel_Load_Running_sql___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  for .
        /// </summary>
        internal static string DatabaseModel_LookupIds__for_ {
            get {
                return ResourceManager.GetString("DatabaseModel_LookupIds__for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking up ids of .
        /// </summary>
        internal static string DatabaseModel_LookupIds_Looking_up_ids_of_ {
            get {
                return ResourceManager.GetString("DatabaseModel_LookupIds_Looking_up_ids_of_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and .
        /// </summary>
        internal static string DatabaseModel_LookupMany2ManyIds__and_ {
            get {
                return ResourceManager.GetString("DatabaseModel_LookupMany2ManyIds__and_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking up many-2-many ids between .
        /// </summary>
        internal static string DatabaseModel_LookupMany2ManyIds_Looking_up_many_2_many_ids_between_ {
            get {
                return ResourceManager.GetString("DatabaseModel_LookupMany2ManyIds_Looking_up_many_2_many_ids_between_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom query for .
        /// </summary>
        internal static string DatabaseModel_Query_Custom_query_for_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Query_Custom_query_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many objects.
        /// </summary>
        internal static string DatabaseModel_QuerySingleOrDefault_Too_many_objects {
            get {
                return ResourceManager.GetString("DatabaseModel_QuerySingleOrDefault_Too_many_objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling back transaction....
        /// </summary>
        internal static string DatabaseModel_RunInTransaction_Rolling_back_transaction___ {
            get {
                return ResourceManager.GetString("DatabaseModel_RunInTransaction_Rolling_back_transaction___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnLinking .
        /// </summary>
        internal static string DatabaseModel_UnLink_UnLinking_ {
            get {
                return ResourceManager.GetString("DatabaseModel_UnLink_UnLinking_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing update operation.
        /// </summary>
        internal static string DatabaseModel_Update_Executing_update_operation {
            get {
                return ResourceManager.GetString("DatabaseModel_Update_Executing_update_operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating .
        /// </summary>
        internal static string DatabaseModel_Update_Updating_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Update_Updating_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating multiple .
        /// </summary>
        internal static string DatabaseModel_Update_Updating_multiple_ {
            get {
                return ResourceManager.GetString("DatabaseModel_Update_Updating_multiple_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be empty.
        /// </summary>
        internal static string DataObjectSqlSerializer_AppendSoftDeleteSql_Collection_cannot_be_empty {
            get {
                return ResourceManager.GetString("DataObjectSqlSerializer_AppendSoftDeleteSql_Collection_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackUrl is not specified.
        /// </summary>
        internal static string FormsModel_BuildRedirectUrl_BackUrl_is_not_specified {
            get {
                return ResourceManager.GetString("FormsModel_BuildRedirectUrl_BackUrl_is_not_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change readonly object {0}.
        /// </summary>
        internal static string FxDataObject_FxDataObject_Cannot_change_readonly_object__0_ {
            get {
                return ResourceManager.GetString("FxDataObject_FxDataObject_Cannot_change_readonly_object__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is not supported.
        /// </summary>
        internal static string InteractionCorrectResponses_GetValue_Requested_variable_is_not_supported {
            get {
                return ResourceManager.GetString("InteractionCorrectResponses_GetValue_Requested_variable_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is write-only.
        /// </summary>
        internal static string InteractionCorrectResponses_GetVariable_Requested_variable_is_write_only {
            get {
                return ResourceManager.GetString("InteractionCorrectResponses_GetVariable_Requested_variable_is_write_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is read-only.
        /// </summary>
        internal static string InteractionCorrectResponses_SetValue_Requested_variable_is_read_only {
            get {
                return ResourceManager.GetString("InteractionCorrectResponses_SetValue_Requested_variable_is_read_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is not supported.
        /// </summary>
        internal static string InteractionObjectives_GetValue_Requested_variable_is_not_supported {
            get {
                return ResourceManager.GetString("InteractionObjectives_GetValue_Requested_variable_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is write-only.
        /// </summary>
        internal static string InteractionObjectives_GetVariable_Requested_variable_is_write_only {
            get {
                return ResourceManager.GetString("InteractionObjectives_GetVariable_Requested_variable_is_write_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is read-only.
        /// </summary>
        internal static string InteractionObjectives_SetValue_Requested_variable_is_read_only {
            get {
                return ResourceManager.GetString("InteractionObjectives_SetValue_Requested_variable_is_read_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is not supported.
        /// </summary>
        internal static string Interactions_GetValue_Requested_variable_is_not_supported {
            get {
                return ResourceManager.GetString("Interactions_GetValue_Requested_variable_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is write-only.
        /// </summary>
        internal static string Interactions_GetVariable_Requested_variable_is_write_only {
            get {
                return ResourceManager.GetString("Interactions_GetVariable_Requested_variable_is_write_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is read-only.
        /// </summary>
        internal static string Interactions_SetValue_Requested_variable_is_read_only {
            get {
                return ResourceManager.GetString("Interactions_SetValue_Requested_variable_is_read_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get rank for item.
        /// </summary>
        internal static string ItemManager_Store_Cannot_get_rank_for_item {
            get {
                return ResourceManager.GetString("ItemManager_Store_Cannot_get_rank_for_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is not supported.
        /// </summary>
        internal static string LnuDataModel_GetValue_Requested_variable_is_not_supported {
            get {
                return ResourceManager.GetString("LnuDataModel_GetValue_Requested_variable_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has invalid ID = {1}.
        /// </summary>
        internal static string LookupHelper_AppendLookupSql_ {
            get {
                return ResourceManager.GetString("LookupHelper_AppendLookupSql_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldnt found relation between {0} and {1}.
        /// </summary>
        internal static string LookupHelper_AppendLookupSql_Couldnt_found_relation_between__0__and__1_ {
            get {
                return ResourceManager.GetString("LookupHelper_AppendLookupSql_Couldnt_found_relation_between__0__and__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldnt fond many-to-many relation between {1} and {2}.
        /// </summary>
        internal static string LookupHelper_AppendMMLinkSql_Couldnt_fond_many_to_many_relation_between__1__and__2_ {
            get {
                return ResourceManager.GetString("LookupHelper_AppendMMLinkSql_Couldnt_fond_many_to_many_relation_between__1__and__" +
                        "2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldnt fond many-to-many relation between {1} and {1}.
        /// </summary>
        internal static string LookupHelper_AppendMMLookupSql_Couldnt_fond_many_to_many_relation_between__1__and__1_ {
            get {
                return ResourceManager.GetString("LookupHelper_AppendMMLookupSql_Couldnt_fond_many_to_many_relation_between__1__and" +
                        "__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register many-to-many relationship. Class {0} doesn&apos;t support {1}.
        /// </summary>
        internal static string LookupHelper_CheckMMSupport_Cannot_register_many_to_many_relationship__Class__0__doesn_t_support__1_ {
            get {
                return ResourceManager.GetString("LookupHelper_CheckMMSupport_Cannot_register_many_to_many_relationship__Class__0__" +
                        "doesn_t_support__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [WARNING] Ignored {0} - {1} relationship because the same is already exists.
        /// </summary>
        internal static string LookupHelper_Put__WARNING__Ignored__0_____1__relationship_because_the_same_is_already_exists {
            get {
                return ResourceManager.GetString("LookupHelper_Put__WARNING__Ignored__0_____1__relationship_because_the_same_is_alr" +
                        "eady_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid many-to-many relationship definition for {0}-{1}.
        /// </summary>
        internal static string LookupHelper_RegisterMMLookup_Invalid_many_to_many_relationship_definition_for__0___1_ {
            get {
                return ResourceManager.GetString("LookupHelper_RegisterMMLookup_Invalid_many_to_many_relationship_definition_for__0" +
                        "___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class {0} is not support {1} so it cannot take participation in Many-To-Many relationship.
        /// </summary>
        internal static string ManyToManyRelationshipAttribute_CheckSupport_Class__0__is_not_support__1__so_it_cannot_take_participation_in_Many_To_Many_relationship {
            get {
                return ResourceManager.GetString("ManyToManyRelationshipAttribute_CheckSupport_Class__0__is_not_support__1__so_it_c" +
                        "annot_take_participation_in_Many_To_Many_relationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AndCondition constructor cannot be created with no subcondition or with only one. You must provide at least two conditions.
        /// </summary>
        internal static string MultipleCondtion_MultipleCondtion_AndCondition_constructor_cannot_be_created_with_no_subcondition_or_with_only_one__You_must_provide_at_least_two_conditions {
            get {
                return ResourceManager.GetString("MultipleCondtion_MultipleCondtion_AndCondition_constructor_cannot_be_created_with" +
                        "_no_subcondition_or_with_only_one__You_must_provide_at_least_two_conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not figure out secured index of {0}. All SecuredDataObject&apos;s classes should be added to {1}.
        /// </summary>
        internal static string ObjectTypeHelper_GetObjectType_Could_not_figure_out_secured_index_of__0___All_SecuredDataObject_s_classes_should_be_added_to__1_ {
            get {
                return ResourceManager.GetString("ObjectTypeHelper_GetObjectType_Could_not_figure_out_secured_index_of__0___All_Sec" +
                        "uredDataObject_s_classes_should_be_added_to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong request (LearnerAttempt ID not specified).
        /// </summary>
        internal static string OpenTestController_PageLoad_Wrong_request__LearnerAttempt_ID_not_specified_ {
            get {
                return ResourceManager.GetString("OpenTestController_PageLoad_Wrong_request__LearnerAttempt_ID_not_specified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You opened {0}({1}) page.
        /// </summary>
        internal static string OpenTestController_ShowCurrent_You_opened__0___1___page {
            get {
                return ResourceManager.GetString("OpenTestController_ShowCurrent_You_opened__0___1___page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataObject {0} must support {1} interface to be a secured object.
        /// </summary>
        internal static string PermissionsManager_CheckSupport_DataObject__0__must_support__1__interface_to_be_a_secured_object {
            get {
                return ResourceManager.GetString("PermissionsManager_CheckSupport_DataObject__0__must_support__1__interface_to_be_a" +
                        "_secured_object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} have no access to do {1} on {2} ID = {3}. Cannot perform delegation.
        /// </summary>
        internal static string PermissionsManager_Delegate_ {
            get {
                return ResourceManager.GetString("PermissionsManager_Delegate_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One and only one of parameters (targetUserID, targetGroupID) must be specified.
        /// </summary>
        internal static string PermissionsManager_Delegate_One_and_only_one_of_parameters__targetUserID__targetGroupID__must_be_specified {
            get {
                return ResourceManager.GetString("PermissionsManager_Delegate_One_and_only_one_of_parameters__targetUserID__targetG" +
                        "roupID__must_be_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One and only one of parameters (userID, groupID) must be specified.
        /// </summary>
        internal static string PermissionsManager_Grand_One_and_only_one_of_parameters__userID__groupID__must_be_specified {
            get {
                return ResourceManager.GetString("PermissionsManager_Grand_One_and_only_one_of_parameters__userID__groupID__must_be" +
                        "_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already initialized.
        /// </summary>
        internal static string PermissionsManager_Initialize__0__is_already_initialized {
            get {
                return ResourceManager.GetString("PermissionsManager_Initialize__0__is_already_initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing Security.
        /// </summary>
        internal static string PermissionsManager_Initialize_Initializing_Security {
            get {
                return ResourceManager.GetString("PermissionsManager_Initialize_Initializing_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can be applied to instance field only but applied to static ({1}.{2}).
        /// </summary>
        internal static string PersistantStateMetaData_GetFieldsDataInternal__0__can_be_applied_to_instance_field_only_but_applied_to_static___1___2__ {
            get {
                return ResourceManager.GetString("PersistantStateMetaData_GetFieldsDataInternal__0__can_be_applied_to_instance_fiel" +
                        "d_only_but_applied_to_static___1___2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid count of target values expected {0} but {1} found.
        /// </summary>
        internal static string PersistantStateMetaData_LoadStateFor_Invalid_count_of_target_values_expected__0__but__1__found {
            get {
                return ResourceManager.GetString("PersistantStateMetaData_LoadStateFor_Invalid_count_of_target_values_expected__0__" +
                        "but__1__found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not supposed to be marked with {2}. Invalid type. Only ValueTypes, strings and classes which implement {1} or {5}. Any combination with {3}&lt;T&gt; and {4}&lt;T&gt; by this types also supported..
        /// </summary>
        internal static string PersistantValueInfo_PersistantValueInfo_Type__0__is_not_supposed_to_be_marked_with__2___Invalid_type__Only_ValueTypes__strings_and_classes_which_implement__1__or__5___Any_combination_with__3__T__and__4__T__by_this_types_also_supported_ {
            get {
                return ResourceManager.GetString("PersistantValueInfo_PersistantValueInfo_Type__0__is_not_supposed_to_be_marked_wit" +
                        "h__2___Invalid_type__Only_ValueTypes__strings_and_classes_which_implement__1__or" +
                        "__5___Any_combination_with__3__T__and__4__T__by_this_types_also_supported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} cannot be persisted because it&apos;s don&apos;t have parameterless constructor.
        /// </summary>
        internal static string PersistantValueInfo_SafeGetConstructor_Type__0__cannot_be_persisted_because_it_s_don_t_have_parameterless_constructor {
            get {
                return ResourceManager.GetString("PersistantValueInfo_SafeGetConstructor_Type__0__cannot_be_persisted_because_it_s_" +
                        "don_t_have_parameterless_constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No groups avalible.
        /// </summary>
        internal static string ReCompilePageController_CreateGroupList_No_groups_avalible {
            get {
                return ResourceManager.GetString("ReCompilePageController_CreateGroupList_No_groups_avalible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users From Group.
        /// </summary>
        internal static string ReCompilePageController_CreateUserList_All_Users_From_Group {
            get {
                return ResourceManager.GetString("ReCompilePageController_CreateUserList_All_Users_From_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group and Theme that your want to recompile.
        /// </summary>
        internal static string ReCompilePageController_PageLoad_Select_Group_and_Theme_that_your_want_to_recompile {
            get {
                return ResourceManager.GetString("ReCompilePageController_PageLoad_Select_Group_and_Theme_that_your_want_to_recompi" +
                        "le", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReCompilation is started.
        /// </summary>
        internal static string ReCompilePageController_ReCompileButtonClick_ReCompilation_is_started {
            get {
                return ResourceManager.GetString("ReCompilePageController_ReCompileButtonClick_ReCompilation_is_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme not selected !!!.
        /// </summary>
        internal static string ReCompilePageController_ReCompileButtonClick_Theme_not_selected____ {
            get {
                return ResourceManager.GetString("ReCompilePageController_ReCompileButtonClick_Theme_not_selected____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to create relation dataobject. Please use methods of ServerModel.DB instead.
        /// </summary>
        internal static string RelTable_RelTable_Impossible_to_create_relation_dataobject__Please_use_methods_of_ServerModel_DB_instead {
            get {
                return ResourceManager.GetString("RelTable_RelTable_Impossible_to_create_relation_dataobject__Please_use_methods_of" +
                        "_ServerModel_DB_instead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is not supported.
        /// </summary>
        internal static string Score_GetValue_Requested_variable_is_not_supported {
            get {
                return ResourceManager.GetString("Score_GetValue_Requested_variable_is_not_supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is write-only.
        /// </summary>
        internal static string Score_GetVariable_Requested_variable_is_write_only {
            get {
                return ResourceManager.GetString("Score_GetVariable_Requested_variable_is_write_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested variable is read-only.
        /// </summary>
        internal static string Score_SetValue_Requested_variable_is_read_only {
            get {
                return ResourceManager.GetString("Score_SetValue_Requested_variable_is_read_only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing ServerModel....
        /// </summary>
        internal static string ServerModel_Initialize_Initializing_ServerModel___ {
            get {
                return ResourceManager.GetString("ServerModel_Initialize_Initializing_ServerModel___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t found DB value for {0}.{1} marked with {2}.
        /// </summary>
        internal static string ServerModel_TableRecordAttributeInitialize_Couldn_t_found_DB_value_for__0___1__marked_with__2_ {
            get {
                return ResourceManager.GetString("ServerModel_TableRecordAttributeInitialize_Couldn_t_found_DB_value_for__0___1__ma" +
                        "rked_with__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course.
        /// </summary>
        internal static string ShareController_courseStr_course {
            get {
                return ResourceManager.GetString("ShareController_courseStr_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curriculum.
        /// </summary>
        internal static string ShareController_curriculumStr_curriculum {
            get {
                return ResourceManager.GetString("ShareController_curriculumStr_curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to delegate this operation..
        /// </summary>
        internal static string ShareController_delegateStr_Allow_to_delegate_this_operation_ {
            get {
                return ResourceManager.GetString("ShareController_delegateStr_Allow_to_delegate_this_operation_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share of {0}: {1} to {2}..
        /// </summary>
        internal static string ShareController_pageCaption_Share_of__0____1__to__2__ {
            get {
                return ResourceManager.GetString("ShareController_pageCaption_Share_of__0____1__to__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can share {0}: {1} to {2}, select operations to be shared..
        /// </summary>
        internal static string ShareController_pageDescription_Here_you_can_share__0____1__to__2___select_operations_to_be_shared_ {
            get {
                return ResourceManager.GetString("ShareController_pageDescription_Here_you_can_share__0____1__to__2___select_operat" +
                        "ions_to_be_shared_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no curriculums assigned for this group..
        /// </summary>
        internal static string StatisticSelectController_noCurriculums_You_have_no_curriculums_assigned_for_this_group_ {
            get {
                return ResourceManager.GetString("StatisticSelectController_noCurriculums_You_have_no_curriculums_assigned_for_this" +
                        "_group_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no groups at all. Create some first..
        /// </summary>
        internal static string StatisticSelectController_noGroups_You_have_no_groups_at_all__Create_some_first_ {
            get {
                return ResourceManager.GetString("StatisticSelectController_noGroups_You_have_no_groups_at_all__Create_some_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic selection..
        /// </summary>
        internal static string StatisticSelectController_pageCaption_Statistic_selection_ {
            get {
                return ResourceManager.GetString("StatisticSelectController_pageCaption_Statistic_selection_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select group and then select curriculum to view statistic..
        /// </summary>
        internal static string StatisticSelectController_pageDescription_Select_group_and_then_select_curriculum_to_view_statistic_ {
            get {
                return ResourceManager.GetString("StatisticSelectController_pageDescription_Select_group_and_then_select_curriculum" +
                        "_to_view_statistic_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string StatisticShowController_fillStatisticTable_Percent {
            get {
                return ResourceManager.GetString("StatisticShowController_fillStatisticTable_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theare are no students in this group..
        /// </summary>
        internal static string StatisticShowController_noStudents_Theare_are_no_students_in_this_group_ {
            get {
                return ResourceManager.GetString("StatisticShowController_noStudents_Theare_are_no_students_in_this_group_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic..
        /// </summary>
        internal static string StatisticShowController_pageCaption_Statistic_ {
            get {
                return ResourceManager.GetString("StatisticShowController_pageCaption_Statistic_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is statisic for group: {0} based on curriculum: {1}. This statistaic is based on passed pages count..
        /// </summary>
        internal static string StatisticShowController_pageDescription_This_is_statisic_for_group___0__based_on_curriculum___1___This_statistaic_is_based_on_passed_pages_count_ {
            get {
                return ResourceManager.GetString("StatisticShowController_pageDescription_This_is_statisic_for_group___0__based_on_" +
                        "curriculum___1___This_statistaic_is_based_on_passed_pages_count_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string StatisticShowController_studentStr_Student {
            get {
                return ResourceManager.GetString("StatisticShowController_studentStr_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string StatisticShowController_totalStr_Total {
            get {
                return ResourceManager.GetString("StatisticShowController_totalStr_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theare are no students in this group..
        /// </summary>
        internal static string StatisticShowCurriculumsController_noStudents_Theare_are_no_students_in_this_group_ {
            get {
                return ResourceManager.GetString("StatisticShowCurriculumsController_noStudents_Theare_are_no_students_in_this_grou" +
                        "p_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic..
        /// </summary>
        internal static string StatisticShowCurriculumsController_pageCaption_Statistic_ {
            get {
                return ResourceManager.GetString("StatisticShowCurriculumsController_pageCaption_Statistic_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is statisic for group: {0} based on curriculums: {1}..
        /// </summary>
        internal static string StatisticShowCurriculumsController_pageDescription_This_is_statisic_for_group___0__based_on_curriculums___1__ {
            get {
                return ResourceManager.GetString("StatisticShowCurriculumsController_pageDescription_This_is_statisic_for_group___0" +
                        "__based_on_curriculums___1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string StatisticShowCurriculumsController_studentStr_Student {
            get {
                return ResourceManager.GetString("StatisticShowCurriculumsController_studentStr_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string StatisticShowCurriculumsController_totalStr_Total {
            get {
                return ResourceManager.GetString("StatisticShowCurriculumsController_totalStr_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0} Dates.
        /// </summary>
        internal static string StudentPageController_ModeButtonClick_Show__0__Dates {
            get {
                return ResourceManager.GetString("StudentPageController_ModeButtonClick_Show__0__Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From this page you can open test or see test results; And see you last {0} result.
        /// </summary>
        internal static string StudentPageController_ShowCommonDescription_From_this_page_you_can_open_test_or_see_test_results__And_see_you_last__0__result {
            get {
                return ResourceManager.GetString("StudentPageController_ShowCommonDescription_From_this_page_you_can_open_test_or_s" +
                        "ee_test_results__And_see_you_last__0__result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have control now. Do you best.
        /// </summary>
        internal static string StudentPageController_ShowDescriptionForControl_You_have_control_now__Do_you_best {
            get {
                return ResourceManager.GetString("StudentPageController_ShowDescriptionForControl_You_have_control_now__Do_you_best" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display themes that you can {0} in selected date.
        /// </summary>
        internal static string StudentPageController_ShowDescriptionForDataSelection_Display_themes_that_you_can__0__in_selected_date {
            get {
                return ResourceManager.GetString("StudentPageController_ShowDescriptionForDataSelection_Display_themes_that_you_can" +
                        "__0__in_selected_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In calendar your see dates when you can {0} test.
        /// </summary>
        internal static string StudentPageController_ShowDescriptionForNodeSelection_In_calendar_your_see_dates_when_you_can__0__test {
            get {
                return ResourceManager.GetString("StudentPageController_ShowDescriptionForNodeSelection_In_calendar_your_see_dates_" +
                        "when_you_can__0__test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only user based permissions can be shared.
        /// </summary>
        internal static string TeacherHelper_Share_Only_user_based_permissions_can_be_shared {
            get {
                return ResourceManager.GetString("TeacherHelper_Share_Only_user_based_permissions_can_be_shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string TeacherHelper_Sort_Percent {
            get {
                return ResourceManager.GetString("TeacherHelper_Sort_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string TeacherHelper_Sort_Student {
            get {
                return ResourceManager.GetString("TeacherHelper_Sort_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TeacherHelper_Sort_Total {
            get {
                return ResourceManager.GetString("TeacherHelper_Sort_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (Click to upload some).
        /// </summary>
        internal static string TeacherObjectsController_noCourses_None__Click_to_upload_some_ {
            get {
                return ResourceManager.GetString("TeacherObjectsController_noCourses_None__Click_to_upload_some_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None (Click to create some).
        /// </summary>
        internal static string TeacherObjectsController_noCurriculums_None__Click_to_create_some_ {
            get {
                return ResourceManager.GetString("TeacherObjectsController_noCurriculums_None__Click_to_create_some_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher objects..
        /// </summary>
        internal static string TeacherObjectsController_pageCaption_Teacher_objects_ {
            get {
                return ResourceManager.GetString("TeacherObjectsController_pageCaption_Teacher_objects_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are listed all your courses and curriculums. Select object to proceed..
        /// </summary>
        internal static string TeacherObjectsController_pageDescription_Here_are_listed_all_your_courses_and_curriculums__Select_object_to_proceed_ {
            get {
                return ResourceManager.GetString("TeacherObjectsController_pageDescription_Here_are_listed_all_your_courses_and_cur" +
                        "riculums__Select_object_to_proceed_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course.
        /// </summary>
        internal static string TeachersListController_courseStr_course {
            get {
                return ResourceManager.GetString("TeachersListController_courseStr_course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to curriculum.
        /// </summary>
        internal static string TeachersListController_curriculumStr_curriculum {
            get {
                return ResourceManager.GetString("TeachersListController_curriculumStr_curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} granted you permission to {1} this {2}.
        /// </summary>
        internal static string TeachersListController_grantedObject__0__granted_you_permission_to__1__this__2_ {
            get {
                return ResourceManager.GetString("TeachersListController_grantedObject__0__granted_you_permission_to__1__this__2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nobody..
        /// </summary>
        internal static string TeachersListController_noTeachers_Nobody_ {
            get {
                return ResourceManager.GetString("TeachersListController_noTeachers_Nobody_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This {0} is your own so you can {1} it..
        /// </summary>
        internal static string TeachersListController_ownObject_This__0__is_your_own_so_you_can__1__it_ {
            get {
                return ResourceManager.GetString("TeachersListController_ownObject_This__0__is_your_own_so_you_can__1__it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share of {0}: {1}..
        /// </summary>
        internal static string TeachersListController_pageCaption_Share_of__0____1__ {
            get {
                return ResourceManager.GetString("TeachersListController_pageCaption_Share_of__0____1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can share {0}: {1} to another teachers, or edit previously done share..
        /// </summary>
        internal static string TeachersListController_pageDescription_Here_you_can_share__0____1__to_another_teachers__or_edit_previously_done_share_ {
            get {
                return ResourceManager.GetString("TeachersListController_pageDescription_Here_you_can_share__0____1__to_another_tea" +
                        "chers__or_edit_previously_done_share_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct Answers.
        /// </summary>
        internal static string TestDetailsController_GetPageTitleType_Correct_Answers {
            get {
                return ResourceManager.GetString("TestDetailsController_GetPageTitleType_Correct_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Answers.
        /// </summary>
        internal static string TestDetailsController_GetPageTitleType_User_Answers {
            get {
                return ResourceManager.GetString("TestDetailsController_GetPageTitleType_User_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User personal info.
        /// </summary>
        internal static string UserInfoController_pageCaption {
            get {
                return ResourceManager.GetString("UserInfoController_pageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your info page. Here you can change your name, email and password. Look up for your roles and groups..
        /// </summary>
        internal static string UserInfoController_pageDescription_This_is_your_info_page__Here_you_can_change_your_name__email_and_password__Look_up_for_your_roles_and_groups_ {
            get {
                return ResourceManager.GetString("UserInfoController_pageDescription_This_is_your_info_page__Here_you_can_change_yo" +
                        "ur_name__email_and_password__Look_up_for_your_roles_and_groups_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many attributes.
        /// </summary>
        internal static string Utils_TryGetAtr_Too_many_attributes {
            get {
                return ResourceManager.GetString("Utils_TryGetAtr_Too_many_attributes", resourceCulture);
            }
        }
    }
}
