//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IUDICO.Common.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseUser
    {
        public int CourseRef { get; set; }
        public System.Guid UserRef { get; set; }
    
        public virtual Course Course { get; set; }
    }
}
